### ISSUE TITLE
Build should reap from aframe src

### ISSUE THREAD

**Issue by subsumo** [ngokevin/aframe-react-boilerplate#15]
`npm install`

WARNING in ./~/aframe/dist/aframe.js
Critical dependencies:
1:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/aframe/dist/aframe.js 1:479-486

**Comment by ngokevin** [comment]
Sorry for delay in responding. We currently ship the dist because when projects using Browserify try to build A-Frame, they'd need to include all of our transforms and stuff.
