### ISSUE TITLE
http://localhost:8080/bundle.js not found

### ISSUE THREAD

**Issue by sirkitree** [ngokevin/aframe-react-boilerplate#19]
Cloned this and ran the commands from the README but continue to get a not found for the bundle. It doesn't seem to be generating. I'm not getting any errors from webpack so it *looks* like it's running ok, but there are no new files generated outside of `node_modules`. 

I tried messing with the `webpack.config.js` a bit, but no luck there either.

Here's my output if you have time to take a look and tell me what might be going wrong: https://gist.github.com/sirkitree/3b6a1574a7ac004dfc13606e1b746b7a

**Comment by RSpace** [comment]
I often have issues running webpack dev server - or any other server - on port 8080. Try running webpack on a different port with the `--port` flag. You can see an example here: https://github.com/RSpace/agile-space/blob/master/package.json

**Comment by sirkitree** [comment]
Thanks that worked. Pull request submitted.
