### ISSUE TITLE
Animation doesn't seem to work out the box

### ISSUE THREAD

**Issue by chloehwang** [ngokevin/aframe-react-boilerplate#30]
I cloned and did npm install - everything looks fine but the box doesn't rotate. Any ideas why? I'm on the latest Chrome.

**Comment by ngokevin** [comment]
I believe it's set up to do it on click or gaze-click.

**Comment by ngokevin** [comment]
I think I need to update animation component. Updating now.

**Comment by ngokevin** [comment]
Fixed
