### ISSUE TITLE
Module build failed: ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by RSpace** [ngokevin/aframe-react-boilerplate#5]
I'm getting this error when I run `npm run serve-js`. It's fixable by adding `require('es6-promise').polyfill();` to `webpack.config.js` and a dev dependency on `es6-promise`. Should I submit a pull request for this workaround, or is there a better to fix it?

**Comment by ngokevin** [comment]
Good catch. Yeah, that sounds to me. You could also try ```require('babel-polyfill')``` since that's already a dep.

**Comment by ngokevin** [comment]
A PR would be great :smiley:
