### ISSUE TITLE
Warning: Failed propType: Invalid prop `children` of type `object` supplied to `Entity`, expected `array`.

### ISSUE THREAD

**Issue by RSpace** [ngokevin/aframe-react-boilerplate#7]
I see this warning when running the boilerplate project locally without making any changes. It seems to be related to the Camera component, where React both doesn't seem to like the `<Entity>` wrapped in an `<Entity>` nor the additional `{...props}` in `<Entity camera look-controls wasd-controls {...props}/>`.

If the wrapping  `<Entity>` and `{...props}` are removed, but then the cursor obviously also disappear. I've so far been unsuccessful in determining exactly why this ends up as an object rather than the array the React validation expects, but it would be nice to not have this warning as the first thing when running the boilerplate.

**Comment by ngokevin** [comment]
Maybe when there's no children, it's an object?

Can we remove the children propType?

**Comment by RSpace** [comment]
Should be solved when this PR is merged into aframe-react: https://github.com/ngokevin/aframe-react/pull/6
